### ISSUE TITLE
[Feature Request] Database

### ISSUE THREAD

**Issue by Kas-tle** [Matt-MX/ReconnectVelocity#1]
It would be really cool if this could connect to an SQL database so that it would work with a multiproxy setup. Great plugin by the way, thank you for all the work you put into it :)

**Comment by Kas-tle** [comment]
No problem. Basically I would just like the current file that contains the UUIDs and last join server to be stored in a database. That way, if I have multiple velocity proxies connecting to the same backends (assuming the naming of the backends is consistent between the proxies), the plugin will then check the database to see what server to send them to, since it's possible their last join was on a different proxy.
The only real change needed for this to work would be the option to store the current uuid and last join list in some sort of database.

**Comment by Matt-MX** [comment]
Added support for MySQL and SQLite!

**Comment by Kas-tle** [comment]
Very cool! Thank you!
