### ISSUE TITLE
Not writing to data.yml

### ISSUE THREAD

**Issue by funnycubeguy** [Matt-MX/ReconnectVelocity#12]
When I connect to a server using velope (load balancer) then switch servers and disconnect the server is not being updated to data.yml so the reconnect doesn't work

**Comment by Matt-MX** [comment]
Perhaps an incompatibility with Velope?

**Comment by BreadChaser** [comment]
Im having the same issue

**Comment by ikifar2012** [comment]
Having this issue too, I have no idea why. I am not using a load balancer

**Comment by Matt-MX** [comment]
Should be fixed in 2.0
