### ISSUE TITLE
[Feature Request] Luckperms integration

### ISSUE THREAD

**Issue by thecmdradama** [Matt-MX/ReconnectVelocity#2]
Hi, 

Would it be possible to look at integrating ReconnectVelocity with LuckPerms? I'm currently using a similar plugin called RememberMe that integrates with LuckPerms for storing the players last server as metadata.  To me, this would be the preferred option to flat file or a separate database.

**Comment by Matt-MX** [comment]
Not a bad idea i can likely add this as an option in the config
