### ISSUE TITLE
Add an auto-reconnect system

### ISSUE THREAD

**Issue by HarvelsX** [Matt-MX/ReconnectVelocity#6]
This feature is quite attractive from a player and server owner;s point of view. 
And of itself is something similar to this plugin on bungee: https://github.com/AoElite/AutoReconnect

**Comment by Matt-MX** [comment]
I might work on something like this, sounds interesting

**Comment by ReclinesMC** [comment]
This plugin pretty much already exists for velocity: https://github.com/Elytrium/LimboReconnect

**Comment by MagicTeaMC** [comment]
> This plugin pretty much already exists for velocity: [Elytrium/LimboReconnect](https://github.com/Elytrium/LimboReconnect)

But it update very slow and not compatible with viaversion

**Comment by kylemarham** [comment]
Would love a reconnect option also

**Comment by Matt-MX** [comment]
This isn't what the project aims at providing so it won't be added unless someone wants to PR it.
