### ISSUE TITLE
Config option to remove velocity.reconnect to enable for everyone 

### ISSUE THREAD

**Issue by TomLewis** [Matt-MX/ReconnectVelocity#7]
Im not currently using a LP on the Velocity proxy as its not really needed in my use case, can you have a toggle to disable requiring a permission to remember which server you was on last, so its global for everyone.

**Comment by voruti** [comment]
I installed LuckPerms just for this permission, so I think this feature would be neat. But on the other hand it's just three lines in the config file:
```yml
name: default
permissions:
- velocity.reconnect
```

**Comment by TomLewis** [comment]
yes, but the problem isnt installing LuckPerms, its the fact that luckperms does not fend well when the proxy is being attacked, so im trying to avoid having to install LuckPerms on the bungee.

**Comment by Matt-MX** [comment]
I mean it's a thing that I am able to add but honestly you should probably have luckperms installed, it's strange to not have it.
I can only see luckperms slowing your proxy down if you were getting a lot of players logging in at once, which sounds like an attack on an offline-mode server, which I don't really support.

**Comment by TomLewis** [comment]
Yes, which is what I said in the previous comment 👍 it's a known attack Vector to time out servers on a proxy, which is reason enough to not install LP at proxy level, as I suffer from many attacks.

**Comment by Matt-MX** [comment]
I'll add it, this thing is due for an update anyway.

**Comment by nvmbrsky** [comment]
Looking forward to this :)

**Comment by HB-Stratos** [comment]
I would also like to have this feature. It's proving quite complicated to set up LP for two fabric servers connected with velocity, and it is just not worth it for a single permission that is needed.
